### ISSUE TITLE
Netflix issue

### ISSUE THREAD

**Issue by rsrrohit** [riverar/wsa-app-compatibility#100]
Can we have a workaround for Netflix's "Device not supported error"? I know that Netflix uses DRM protection on 1080p+ content and so it won't run on any non-compatible device. But I hope if we could use an older version or modified apk that bypasses that error.

**Comment by riverar** [comment]
@rsrrohit Sorry Rohit, we can't offer support here for apps in WSA. Would maybe try Reddit or other technical communities. If anyone else can help Rohit, feel free to reply here though!
