### ISSUE TITLE
Konosuba Fantastic Days (1.12.8) Crashes to desktop after attempting any login method

### ISSUE THREAD

**Issue by homerjacksum** [riverar/wsa-app-compatibility#140]
tried facebook, google and even local account to try to get the game running, no success

**Comment by MilkFlavor** [comment]
Same problem. Any update?

**Comment by MilkFlavor** [comment]
It's most likely a problem with google and not WSA it's self.

**Comment by riverar** [comment]
Sorry @ homerjacksum, we can't offer support for WSA or apps here. Try posting over at https://www.reddit.com/r/WSA/, good luck!
