### ISSUE TITLE
WSA update (2204.40000.15.0)

### ISSUE THREAD

**Issue by Rexogamer** [riverar/wsa-app-compatibility#144]
Hey! Just wanted to note that [2204.40000.15.0](https://blogs.windows.com/windows-insider/2022/05/20/update-to-windows-subsystem-for-android-on-windows-11/) has been released to the Dev channel - this, among other things, updates Android to 12.1. A few of the apps listed might not work anymore. Thanks for the list ^^

**Comment by PoisonDarterz** [comment]
might help to note by creating pull request after testing the appropriate apps

**Comment by riverar** [comment]
Thanks for the reminder! A contributor added the column so I think we're good to go moving forward. Closing this for now but feel free to continue the discussion if needed.
