### ISSUE TITLE
Star+ app

### ISSUE THREAD

**Issue by luanfsp** [riverar/wsa-app-compatibility#158]
Can't use Star+ to watch any content. Just get a error. I think is related to content rights.

Can you help me make it work if possible?

**Comment by pratyakshm** [comment]
@riverar I don't think this is workable without use of some shady modifications, also this is outside of this repository's spectrum. Shall I close it?

**Comment by riverar** [comment]
Yep, sadly we can't help with circumvention of DRM, which is likely required here.
