### ISSUE TITLE
Has anyone been able to make screen overlay (e.g. picture in picture, or hud over other apps) work?

### ISSUE THREAD

**Issue by terrytw** [riverar/wsa-app-compatibility#171]
I am using app ops, and it has a notification overlay which shows whether the app is using certain permissions. It does not seem to work ATM. Anyone got it to work?

**Comment by riverar** [comment]
If you can reproduce this issue with any app, I'd recommend putting together a formal issue and file it here https://github.com/microsoft/WSA/issues.
