### ISSUE TITLE
League of Legends Wild Rift not working correctly

### ISSUE THREAD

**Issue by GhelloZ** [riverar/wsa-app-compatibility#223]
i just sideloaded wild rift on my pc nad it opens normally but i'm instally greeted with a message saying that the game was installed on an unofficial platform and wont let me play
![immagine](https://user-images.githubusercontent.com/56313248/202430685-78ef70a0-ef3f-485c-89b1-be7fc8817ed6.png)
any workaround?

**Comment by wizpizz** [comment]
This issue can be closed as the latest version of Wild Rfit seems to working fine on Android 13

**Comment by riverar** [comment]
@wizpizz Great, thanks for the update!
