### ISSUE TITLE
URI `wsa://com.android.settings` is supported

### ISSUE THREAD

**Issue by exsequi** [riverar/wsa-app-compatibility#233]
> Some URIs are not supported in WSA, such as:
> 
> wsa://com.android.settings

Now, `wsa://com.android.settings` is supported on WSA.

- WSA 2210.40000.7.0
- Win11 22H2 22621.963

![Snipaste_2022-12-20_22-11-56](https://user-images.githubusercontent.com/10898245/208686768-4ee7b177-a017-49ce-941b-07a0e6b71c52.png)

**Comment by theipster** [comment]
I can confirm it also works for WSA version 2209.40000.28.0 (OS build 22621.963).

**Comment by riverar** [comment]
Nice, any idea when this was first introduced? Should we just go with `2209.40000.28.0` for now?
