### ISSUE TITLE
QSC Touchmix-30 Control v. 2.0.11630 not working with the lastest WSA based on Android 12/13

### ISSUE THREAD

**Issue by calessio86** [riverar/wsa-app-compatibility#249]
I cannot run QSC Touchmix-30 Control app (version 2.0.11630) on the lastest WSA releases based on Android 12 and 13.
I tried WSA Build 2203.40000.3.0 (the last version based on Android 11) and the app works, but on this build there are some network issue (such as internet connection) and are not implemented advance network features.

Using WSA 2209.40000.26.0 and 2301.40000.7.0 the app go in crash.... When I launch it, the system try to open app but after 1 second close it automatically.
Using WSA 2203.40000.3.0 the app works fine.
The same app works fine on my smartphone (Mi 10 T pro) with android 12 SKQ1.211006.001

**Comment by riverar** [comment]
Sorry @calessio86, we can't offer support for WSA or apps here. Feel free to edit the table if the app isn't working correctly. For additional help, try posting over at https://www.reddit.com/r/WSA/, good luck!
