### ISSUE TITLE
Gaming Compatibility Update

### ISSUE THREAD

**Issue by mjkim0727** [riverar/wsa-app-compatibility#252]
![Screenshot 2023-03-17 192902](https://user-images.githubusercontent.com/78864678/225879915-e40e16e9-0bf5-4f21-89b5-bf5b4845183b.png)

![Screenshot 2023-03-17 193403](https://user-images.githubusercontent.com/78864678/225880825-9129e40b-0514-45e8-b531-f3bcf6d3848d.png)

This error message(이 기기에서는 플레이할 수 없습니다) means "You can't playing at this device.".

WSA Build is 2301.40000.4.0(Android 13) and Application version is 1.1.2.

**Comment by kuroehanako** [comment]
![Screenshot 2023-03-17 194012](https://user-images.githubusercontent.com/78864678/225882388-8ee9fa07-4d36-4eb8-ac33-d57b82da93bf.png)

Also, Kartrider Rush+ can run on WSA. But, Touchscreen is recommended.

**Comment by riverar** [comment]
Thanks @mjkim0727, feel free to edit the table if that game is no longer working.
