### ISSUE TITLE
WhatsApp incompatible?

### ISSUE THREAD

**Issue by dreamflasher** [riverar/wsa-app-compatibility#263]
I have installed WhatsApp but can't get past "verify phone number", I have two buttons "Continue" and "Verify with SMS", and nothing happens when I click on either button.

**Comment by riverar** [comment]
Sorry @dreamflasher, we can't offer support for WSA or apps here. Try posting over at https://www.reddit.com/r/WSA/, good luck!

**Comment by dreamflasher** [comment]
@riverar Not necessarily looking for help, but your list is wrong. WhatsApp is not compatible anymore, so it should be taken off the list.
