### ISSUE TITLE
Cannot differentiate between what's compatible vs what's not due to red-green colorblindness

### ISSUE THREAD

**Issue by iammarxg** [riverar/wsa-app-compatibility#33]
Hi! The colors you're using to show whether an app is compatible or not with WSA, are really hard for the majority of people with CVD (Color Vision Deficiency) to differentiate.

CVD (or colorblindness as people usually call it) affects 1 in 12 men worldwide (about 8% of all men), and it affects 1 in 200 women worldwide (which is about 0.5% of all women).
 
This could be solved by changing the legend to also accommodate shapes, without having to change the colors.
Example:

- 🟩 Works (unchanged)
- 🆖 Works, but needs Google Mobile Services (unchanged)
- ⭐ Works, but with some notable problems (🟨 to ⭐)
- 🔴 Broken (🟥 to 🔴)

[Here](https://www.getfeedback.com/resources/ux/how-to-design-for-color-blindness/)'s more info on how to design for colorblindness.

You don't have to do this, I'm just putting it as a heads-up for other people to see too.

**Comment by Ratulhasan14789** [comment]
well Can switch to ✔️ ❌ ⚠️ 🆖
best in all aspects

**Comment by iammarxg** [comment]
Yeah that would work too

**Comment by riverar** [comment]
Agreed, big problem for deuternopia/protanopia folks. Wish GitHub extended Markdown to native support table glyphs for stuff like this!

**Comment by Rexogamer** [comment]
I would advise using ✅ over ✔️ as (at least on iOS) the latter doesn't show well when using dark mode.

**Comment by pratyakshm** [comment]
> I would advise using ✅ over ✔️ as (at least on iOS) the latter doesn't show well when using dark mode.

We already are using that emoji.
![image](https://user-images.githubusercontent.com/54220235/140604384-4f28551a-58e0-4b6a-87cd-a591bd42e26a.png)
