### ISSUE TITLE
Add compatibility list with GSM patch

### ISSUE THREAD

**Issue by Ratulhasan14789** [riverar/wsa-app-compatibility#36]
lots of people are now applying tge GSM patch thats uproaring the internet, so maybe a list of compatitable (and not) apps with GSM patch can be created.
Good side: people can decide if s/he should apply the patch (like app don't work even after using GSM) also lots of apps are working with GSM (like opera mini and many more)

**Comment by riverar** [comment]
@Ratulhasan14789 We have 🆖 to serve as an indicator for when Google Mobile Services (GMS) are needed. This is meant to mean "if GMS is available, everything else should work". Are you saying we need another state where perhaps the app may still be broken?

**Comment by Ratulhasan14789** [comment]
well i'm in a bit confused state right now. the NG sign do mean that when the app tells that it needs GSM
however most apps don't even detect and alert it (happened to me with opera mini, crashed on start up, then i patched the WSA with GSM, it works fine. So i didn't submit the app wheather to put it not working or the NG)
I hope i managed to explain.

**Comment by riverar** [comment]
@Ratulhasan14789 Makes sense. If you patched it and it now works, feel free to submit a PR with 🆖 with maybe some notes (e.g. "Crashes on start unless GMS available").

**Comment by Ratulhasan14789** [comment]
maybe i should avoid adding some apps since i am using GSM. trying online apps now.

**Comment by riverar** [comment]
Think we're done here, closing. If we missed something, let us know!
